Appointment/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^main/', include('apps.appointment.urls', namespace='home')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
]

apps/appointment/urls.py
from django.conf.urls import url 
from . import views

urlpatterns=[
	url(r'^$', views.index, name='index'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
]

apps/dashboard/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.dashboard, name='dashboard'),
	url(r'^add_appointment$', views.add_appointment, name='add_appointment'),
	url(r'^(?P<id>\d+)/delete$', views.delete, name='delete'),
	url(r'^(?P<id>\d+)/edit$', views.edit, name='edit'),
	url(r'^(?P<id>\d+)/update$', views.update, name='update'),
	url(r'^logout$', views.logout, name='logout')
]

apps/appointment/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt
from django.contrib import messages

EMAIL_REGEX = re.compile(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")
NAME_REGEX = re.compile(r'(^[a-zA-Z])')
class UserManager(models.Manager):
	def register(self, first_name, last_name, email, password, password_confirm, birthday):
		errors = []
		if len(first_name) < 3:
			errors.append("Must be atleast 2 characters first_name")
		if len(last_name) < 3:
			errors.append("Must be atleast 2 characters last_name")
		if not NAME_REGEX.match(first_name):
			errors.append("First Name must be all characeters")
		if not NAME_REGEX.match(last_name):
			errors.append("Last Name must be all characters")
		if not EMAIL_REGEX.match(email):
			errors.append("Not a Valid Email Format")
		emails = User.objects.filter(email=email)
		if len(emails) > 0:
			errors.append("Email already exists")

		if len(password) < 8:
			errors.append("Password must be atleast 8 characeters long")
		if not password == password_confirm:
			errors.append("Passwords must match")

		print errors
		if errors:
			return {'error': errors}
		else:
			if len(User.objects.all()) == 0:
				hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
				User.objects.create(first_name=first_name, last_name=last_name, email=email, password=hashed, birthday=birthday)
				return {'theuser': errors}
			else:
				hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
				User.objects.create(first_name=first_name, last_name=last_name, email=email, password=hashed, birthday=birthday)
				return {'theuser': errors}
	def login(self, email, password):
		errors = []
		user = User.objects.filter(email= email)
		if len(user) > 0:
			if bcrypt.hashpw(password.encode(), user[0].password.encode()) == user[0].password:
				return {'theuser': "Valid login"}
			else:
				return {"error": "The password and email does not match"}
		else:
			return {"error": "This email does not exist"}
class User(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=1000)
	birthday = models.DateField()
	objects = UserManager()

apps/dashboard/models.py
from __future__ import unicode_literals
from ..appointment.models import User
from django.db import models
import datetime


class AppointmentManager(models.Manager):
	def add_appointment(self, date, time, task, user_id):
		dateNow=datetime.date.today()
		timeNow=datetime.datetime.now().time()
		if dateNow.strftime('%m/%d/%Y') > date:
			status=3
		elif dateNow.strftime('%m/%d/%Y') == date:
			if timeNow.strftime('%H:%M') > time:
				status=3
			else:
				status=1
		else:
			status=1
		appointment=Appointment.objects.create(task=task, date=date, time=time, status=status)
		User.objects.get(id=user_id).appointments.add(appointment)
	def delete(self, id, user_id):
		Appointment.objects.get(id=id).delete()
		pass
	def update(self, id, task, status, date, time):
		Appointment.objects.filter(id=id).update(task=task, status=status, date=date, time=time)
		pass
		
class Appointment(models.Model):
	task=models.CharField(max_length=1000)
	date=models.DateField()
	time=models.TimeField()	
	status=models.IntegerField()
	user=models.ForeignKey(User, related_name='appointments', null=True)
	objects = AppointmentManager()

apps/appointment/views.py
from django.shortcuts import render, redirect
from .models import User
def index(request):
	context= {
		'users': User.objects.all(),
	}
	return render(request, 'appointment/index.html', context)
def register(request):
	if request.method == 'POST':
		user = User.objects.register(request.POST['first_name'], request.POST['last_name'], request.POST['email'], request.POST['password'], request.POST['password_confirm'], request.POST['birthday'])
		if 'error' in user:
			print "Not a Valid Registration form"
			return redirect('home:index')
		if 'theuser' in user:
			print "Valid Registration Form"
			return redirect('home:index')	
	return redirect('home:index')
def login(request):
	if request.method == 'POST':
		response=User.objects.login(request.POST['email'], request.POST['password'])
		if 'error' in response:
			print 'invalid login'
			return redirect('home:index')
		if 'theuser' in response:
			print 'successful login'
			user=User.objects.get(email=request.POST['email'])
			request.session['id'] = user.id
			return redirect('dashboard:dashboard')
	return redirect('home:index')

apps/dashboard/views.py
from django.shortcuts import render, redirect
from .models import Appointment
from ..appointment.models import User
import datetime

def dashboard(request):
	dateNow=datetime.date.today()
	context= {
		'users': User.objects.filter(id=request.session['id']),
		'appointments': Appointment.objects.filter(user__id=request.session['id']).filter(date=dateNow.strftime('%Y-%m-%d')),
		'other_appointments': Appointment.objects.filter(user__id=request.session['id']).filter(date__gt=dateNow.strftime('%Y-%m-%d')),
		'today_date': dateNow
	}
	return render(request, 'dashboard/dashboard.html', context)
def add_appointment(request):
	if request.method=='POST':
		appointments=Appointment.objects.add_appointment(request.POST['date'], request.POST['time'], request.POST['task'], request.session['id'])
		print appointments
	return redirect('dashboard:dashboard')
def delete(request, id):
	Appointment.objects.delete(id, request.session['id'])
	return redirect('dashboard:dashboard')
def edit(request, id):
	context={
		'appointments': Appointment.objects.filter(id=id),
	}
	return render(request, 'dashboard/edit.html', context)
def update(request, id):
	Appointment.objects.update(id, request.POST['task'], request.POST['status'], request.POST['date'], request.POST['time'])
	return redirect('dashboard:dashboard')
def logout(request):
	request.session.flush()
	return redirect('home:index')

apps/appointment/templates/appointment/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>
	<div>
		<h1>Registration</h1>
		<form action="{% url 'home:register' %}" method="post">
			{% csrf_token %}
			<label>First Name: </label>
			<input type="text" name="first_name"><br>

			<label>Last Name: </label>
			<input type="text" name="last_name"><br>

			<label>Email: </label>
			<input type="text" name="email"><br>

			<label>Password: </label>
			<input type="password" name="password"><br>

			<label>Confirm Password: </label>
			<input type="password" name="password_confirm"><br>

			<label>Birthday:</label>
			<input type="date" name="birthday"><br>

			<input type="submit" name="submit" value="Register!">
		</form>
	</div>

	<div>
		<h1>Login</h1>
		<form action="{% url 'home:login' %}" method="post">
			{% csrf_token %}
			<label>Email: </label>
			<input type="text" name="email"><br>

			<label>Password: </label>
			<input type="password" name="password"><br>

			<input type="submit" name="submit" value="Login">
		</form>
	</div>
    {% for user in users %}
        {{ user.first_name }} {{ user.email }} {{ user.birthday }}<br>
    {% endfor %}

</body>
</html>

apps/dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Dashboard Admin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script>
		function clicked(e){
		  if(!confirm('Are you sure?'))e.preventDefault();
		}
	</script>
</head>
<body>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          
        </div>
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li></li>
        </ul>
      </div>
    </nav>
  </div>
</div>
<dir class="row">
	<div class="col-sm-1"></div>
	<div class="col-sm-2">
		<h4>Manage Users</h4>
    <a href="{% url 'dashboard:logout' %}">log out</a>
    <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
	</div>
	<div class="col-sm-7"></div>
	<div class="col-sm-1">
	</div>
</dir>
{% for user in users %}
<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
      	<th>Task</th>
        <th>Time</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    	{% for appointment in appointments %}
    		<tr>
          <th>{{ appointment.task }}</th>
          <th>{{ appointment.time }} {{appointment.date}}</th>
          <th>
            {% if appointment.status == 1 %}
              Pending
            {% elif appointment.status == 2 %}
              Done
            {% else %}
              Missed
            {% endif %}
          </th>
    			<th>
    				<a href="{% url 'dashboard:edit' id=appointment.id %}">Edit</a>
    				<a href="{% url 'dashboard:delete' id=appointment.id %}" onclick='clicked(event)'>Remove</a>
    			</th>
    		</tr>
    	{% endfor %}
    </tbody>
  </table>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Task</th>
        <th>Time</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for appointment in other_appointments %}
        <tr>
          <th>{{ appointment.task }}</th>
          <th>{{ appointment.time }}{{appointment.date}}</th>
          <th>
            {% if appointment.status == 1 %}
              Pending
            {% elif appointment.status == 2 %}
              Done
            {% else %}
              Missed
            {% endif %}
          </th>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <h3>Add Appointment</h3>
  <form action=" {% url 'dashboard:add_appointment' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="date">Date:</label>
    <input type="date" class="form-control" id="date" name="date">
  </div>
  <div class="form-group">
    <label for="time">Time</label>
    <input type="time" class="form-control" id="time" name="time">
  </div>
  <div class="form-group">
    <label><input type="text" name="task"> Task</label>
  </div>
  <button type="submit" class="btn btn-default">Add</button>
  </form>
</div>
{% endfor %}


</body>
</html>

apps/dashboard/templates/dashboard/edit.html
<!DOCTYPE html>
<html>
<head>
	<title>Edit page</title>
</head>
<body>
    <a href="{% url 'dashboard:logout' %}">log out</a>
    <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>

	{% for appointment in appointments %}
	<div>
		<h1>Edit</h1>
		<form action="{% url 'dashboard:update' id=appointment.id %}" method="post">
			{% csrf_token %}
			<label>Task: </label>
			<input type="text" name="task" value={{appointment.task}}><br>

			<label>Status</label>
			<select name='status'>
				<option value=2>Done</option>
				<option value=1>Pending</option>
				<option value=3>Missed</option>
			</select>

			<label>Date:</label>
			<input type="date" name="date"><br>
			<label>Time:</label>
			<input type="time" name="time"><br>

			<input type="submit" name="submit" value="Update">
		</form>
	</div>
	{% endfor %}
</body>
</html>